import type { Metadata } from "next"
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { BackHeader } from "@/components/Navigation/BackHeader"
import { NavigationProvider } from "@/components/Providers/Navigation"
import { OnlinePresenceProvider } from "@/components/Providers/Online"
import { Toaster } from "@/components/ui/sonner"

const jetbrainsMonoHeading = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
  preload: true,
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        jetbrainsMonoHeading.variable,
        "dark",
      )}
    >
      <body className="min-h-full bg-[color-background] flex justify-center items-center">
        <Toaster />
        <OnlinePresenceProvider />
        <div className="flex justify-center items-center w-full relative">
          <div className="flex w-full max-w-[600px] flex-col">
            <NavigationProvider>
              <BackHeader />
              {children}
            </NavigationProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
